### ISSUE TITLE
The page rendering error when closing a tab between two tabs

### ISSUE THREAD

**Issue by iamSmallY** [ant-design-blazor/demo-reuse-tabs#2]
![ezgif-6-d7cfdcd4e621](https://user-images.githubusercontent.com/45689960/130362537-a52a9419-0df3-4966-b60e-2628efddfac2.gif)

Like the gif above, after closing a tab between two tabs, the page will be rendered in the right.
![1](https://user-images.githubusercontent.com/45689960/130362560-f6817e76-83e8-451c-b44d-33d5030a8c44.png)

I have changed the `TargetFramework` from `net 6.0` to `net 5.0`, I don’t know if the bug is caused by this reason.

**Comment by ElderJames** [comment]
Fixed.
