### ISSUE TITLE
Suspected  a  bug ，about “AuthorizeReuseTabsRouteView ”

### ISSUE THREAD

**Issue by aihui109** [ant-design-blazor/demo-reuse-tabs#7]
replace to "ReuseTabsRouteView",can be work. otherwise，No effect。
https://github.com/aihui109/ApenHis/blob/d4c8cff7e69666896faf83ab37bbffb8a8042509/src/ApenHis.Blazor/App.razor#L5

**Comment by ElderJames** [comment]
We have been remove the ReuseTabsRouteView
