### ISSUE TITLE
Possible to overwrite the css:    

### ISSUE THREAD

**Issue by Zero-Xiong** [ant-design-blazor/demo-reuse-tabs#9]
![margin](https://github.com/ant-design-blazor/demo-reuse-tabs/assets/13866194/370a6aad-e9e7-4086-9d05-430830fcd241)

Possible to overwrite the CSS as showing above?

It could save some space in some cases.

**Comment by ElderJames** [comment]
Thanks for contacting us @Zero-Xiong , here is the official doc: https://learn.microsoft.com/en-us/aspnet/core/blazor/components/css-isolation?view=aspnetcore-7.0#child-component-support

- You need to add a html element like `div`, `span`
- Using `div:: ant-tabs-nav` to override the style of child components.

**Comment by Zero-Xiong** [comment]
how do you make it works? I tried as below, seems like no use

![margin1](https://github.com/ant-design-blazor/demo-reuse-tabs/assets/13866194/014602d8-f7b7-4e43-9149-450b402b261e)

**Comment by Zero-Xiong** [comment]
Never mind, I know how to do it. Thanks!


`::deep div > div.ant-tabs-nav {
	margin: 0;
}
`

**Comment by ElderJames** [comment]
Sorry, please try `div::deep ant-tabs-nav `
